/* ============================================================================
 * supplier.c -- Supplier process.
 *
 * Usage:
 *   ./supplier <supplier_id> <config_file>
 *
 * Reads its .conf (item_id,quantity_per_shipment,interval_seconds) and
 * periodically sends a RestockMsg per item on RESTOCK_FIFO, each with its own
 * interval.
 * ============================================================================ */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <signal.h>
#include <errno.h>
#include "common.h"

#define MAX_CONF_ITEMS 1024
#define LINE_BUF        256
#define CONF_HEADER     "item_id,quantity_per_shipment,interval_seconds"

/*one item of the config file*/
typedef struct {
    int item_id;
    int quantity;
    int interval;     /* seconds between deliveries        */
    int countdown;    /* seconds left to the next delivery */
} RestockSchedule;

/* Termination flag */
static volatile sig_atomic_t shutdown_flag = 0;

/* SIGTERM/SIGINT handler */
static void handle_stop(int sig) { (void)sig; shutdown_flag = 1; }

/* ====== Parse the .conf ====================================================
 * Strict: a malformed line aborts startup (the .conf is generated by
 * bootstrap.sh).
 * ========================================================================== */
static int load_config(const char *path, RestockSchedule *plan, int max_items)
{
    int fd = open(path, O_RDONLY);
    if (fd < 0) {
        fprintf(stderr, "[SUPPLIER] open config '%s': %s\n",
                path, strerror(errno));
        return -1;
    }

    char line[LINE_BUF];

    /* Mandatory header. */
    if (read_line_from_fd(fd, line, sizeof(line)) <= 0 ||
        strncmp(line, CONF_HEADER, strlen(CONF_HEADER)) != 0) {
        fprintf(stderr, "[SUPPLIER] '%s': missing/invalid header."
                        "(expected '%s')\n", path, CONF_HEADER);
        close(fd);
        return -1;
    }

    int count = 0;
    ssize_t n;
    while (count < max_items && (n = read_line_from_fd(fd, line, sizeof(line))) > 0) {
        if (line[0] == '\r' || line[0] == '\n' || line[0] == '\0') continue;

        RestockSchedule *it = &plan[count];
        if (sscanf(line, "%d,%d,%d",
                   &it->item_id, &it->quantity, &it->interval) != 3) {
            fprintf(stderr, "[SUPPLIER] '%s': malformed line: %s",
                    path, line);
            close(fd);
            return -1;
        }
        if (it->item_id < 1 || it->quantity < 1 || it->interval < 1) {
            fprintf(stderr, "[SUPPLIER] '%s': non-positive values: %s",
                    path, line);
            close(fd);
            return -1;
        }
        it->countdown = it->interval;   /* first delivery after one interval */
        count++;
    }
    if (n < 0) {
        fprintf(stderr, "[SUPPLIER] failed to read '%s': %s\n", path, strerror(errno));
        close(fd);
        return -1;
    }
    close(fd);
    if (count == 0) {
        fprintf(stderr, "[SUPPLIER] '%s': no valid items.\n", path);
        return -1;
    }
    return count;
}

/* ====== MAIN ============================================================== */
int main(int argc, char *argv[])
{
    if (argc != 3) {
        fprintf(stderr, "Usage: %s <supplier_id> <config_file>\n", argv[0]);
        return ERR_USAGE;
    }
    int supplier_id = atoi(argv[1]);
    if (supplier_id <= 0) {
        fprintf(stderr, "[SUPPLIER] supplier_id must be >= 1\n");
        return ERR_USAGE;
    }

    /* Signals */
    setup_handler(SIGTERM, handle_stop);
    setup_handler(SIGINT,  handle_stop);
    setup_handler(SIGPIPE, SIG_IGN);

    RestockSchedule schedule[MAX_CONF_ITEMS];
    int n_items = load_config(argv[2], schedule, MAX_CONF_ITEMS);
    if (n_items < 0) return ERR_IO;

    /* Blocking open of RESTOCK_FIFO.
     * Retry on EINTR unless a termination signal arrived. */
    int fifo_fd = -1;
    while (fifo_fd < 0 && !shutdown_flag) {
        fifo_fd = open(RESTOCK_FIFO, O_WRONLY);
        if (fifo_fd < 0) {
            if (errno == EINTR) continue;
            fprintf(stderr, "[SUPPLIER %d] failed to open '%s': %s\n",
                    supplier_id, RESTOCK_FIFO, strerror(errno));
            return ERR_IO;
        }
    }
    if (fifo_fd < 0) return ERR_OK;   /* SIGTERM during the open */



    while (!shutdown_flag) {
        /* smallest countdown = how long we may sleep */
        int min_cd = schedule[0].countdown;
        for (int i = 1; i < n_items; i++)
            if (schedule[i].countdown < min_cd) min_cd = schedule[i].countdown;

        /* sleep: interrupted sleep returns the seconds NOT slept -> slept is
         *    the time actually elapsed */
        unsigned int left  = sleep((unsigned int)min_cd);
        int          slept = min_cd - (int)left;
        if (shutdown_flag) break;

        /* update countdowns and ship the items that reached zero */
        for (int i = 0; i < n_items; i++) {
            schedule[i].countdown -= slept;
            if (schedule[i].countdown > 0) continue;

            RestockMsg msg = { supplier_id, schedule[i].item_id, schedule[i].quantity };
            if (write_all(fifo_fd, &msg, sizeof(msg)) < 0) {
                fprintf(stderr, "[SUPPLIER %d] failed to write on FIFO: %s\n", supplier_id, strerror(errno));
                close(fifo_fd);
                return ERR_WAREHOUSE_DOWN;
            }
           schedule[i].countdown = schedule[i].interval;   /* re-arm the timer */
        }
    }

    close(fifo_fd);

    return ERR_OK;
}